# Generated by Django 4.2.13 on 2024-05-18 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Today_Outfit_App", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
