# Generated by Django 4.2.13 on 2024-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Today_Outfit_App", "0005_remove_fashionitem_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fashionitem",
            name="item_id",
            field=models.IntegerField(default=0),
        ),
    ]
