# Generated by Django 4.2.13 on 2024-05-19 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Today_Outfit_App", "0006_fashionitem_item_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FashionItem",
        ),
    ]
