# Generated by Django 4.2.13 on 2024-05-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Today_Outfit_App', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='likes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
