# Generated by Django 4.2.13 on 2024-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Today_Outfit_App', '0009_alter_fashionitem_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='item_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
