# Generated by Django 5.1 on 2024-08-22 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Today_Outfit_App", "0011_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
